회원가입 페이지 리팩터링
girok-web/girok-web pull request #15
Opened 2024-01-23 07:33 UTC by cruelladevil

## 🔨 작업 내용

- [x] InputField 및 SignForm의 Input 리팩터링
- [x] react-hook-form 적용
  - [ ] validation 적용
- [ ] react query 적용
  - [ ] 에러 핸들링
- [ ] 퍼널 적용

## 💬 리뷰 참고사항

> 원활한 리뷰를 위해 전달하고 싶은 맥락(특정 파일, 디렉터리 등등)  
> 리뷰어가 특별히 봐주었으면 하는 부분

InputField와 SignForm의 Input을 먼저 적용하였습니다.
Input에 대한 상태가 많아짐에 따라 react-hook-form으로 간소화하여 상태관리 하였습니다.
지금까지 변경사항 서로 확인 후 퍼널 적용하고 마무리하려고 합니다.

💬 validation 및 react query 적용하여 에러 핸들링은 따로 이슈 파서 진행할지 이 PR에서 마무리할지 결정해야 할 것 같습니다!

## #️⃣ 연관된 이슈

> 연관된 이슈 번호를 모두 작성

close #14

2024-01-23 10:16 UTC, jw-r requested changes
코드 잘 확인했습니다!
많이 깔끔해진 것 같네요🥳

react-hook-form의 에러 핸들링과
react-query의 에러 핸들링은 그 성격이 많이 다를 것이라고 생각하는데 정확히 어떤 문제에 대해 고민하고 계신지 궁금해요!

2024-01-23 10:16 UTC, jw-r commented on src/auth/signup/components/SignupPassword.tsx
정말 깔끔해졌네👍

2024-01-23 10:16 UTC, jw-r commented on src/shared/InputField.tsx
> +        })}
`현재의 형태 + react-hook-form을 사용하지 않음`이라면
하나의 Input당 handleChangeInput 함수를 작성해주어야 할 것 같습니다

다음과 같이 하나의 이벤트 핸들러로 처리하기 위해서 input jsx는 name 속성을 가지고 있어야 할 것 같아요
```javascript
const hanldeChangeInput = (e) => {
  const { name, value } = e.target;
  setFormData((prev) => ({
    ...prev,
    [name]: value,
  ))
}
```

2024-01-23 10:16 UTC, jw-r commented on src/shared/InputField.tsx
> +        })}
react-hook-form을 사용하는 이상 name 속성은 register의 반환값으로 받게 되겠지만 그렇지 않은 경우 어떻게하면 좋을까요?
react-hook-form을 도입하면 왠만하면 register를 사용할 것이라고 생각하지만 정민님의 의견도 궁금하네요!

2024-01-23 10:42 UTC, cruelladevil commented on src/shared/InputField.tsx
> +        })}
children은 InputElement 하나로 제한되어 있습니다!

```ts
interface InputProps extends HTMLAttributes<HTMLDivElement> {
  // ...
  children: ReactElement;
}

export default function InputField({ type, label, children, bottomText, ...props }: InputProps) {
  const child = Children.only(children);
  // ...
}
```

2024-01-23 10:44 UTC, cruelladevil commented on src/shared/InputField.tsx
> +        })}
> react-hook-form을 사용하는 이상 name 속성은 register의 반환값으로 받게 되겠지만 그렇지 않은 경우 어떻게하면 좋을까요?
react-hook-form을 도입하면 왠만하면 register를 사용할 것이라고 생각하지만 정민님의 의견도 궁금하네요!

input의 name 속성 말씀하시는 것이라면 clone이 되어서 prop이 넘겨질 것 같습니다!

2024-01-23 11:07 UTC, cruelladevil commented
에러 핸들링에 대한 설명이 부족했던 것 같네요!

아래 예시와 같이 이미 회원가입한 이메일로 verification을 요청할 때 응답으로 400이 오게 되면,
해당 에러코드에 대해 bottomText로 `This email is already taken.`을 보여준다던가 하는 에러 처리였습니다!

```ts
const {
  register,
  handleSubmit,
  formState: { errors },
  setError,
} = useForm<FormFields>();

const { mutate } = useEmailVerificationMutation();

const submitEmail: SubmitHandler<FormFields> = ({ email }) => {
  mutate(
    { email },
    {
      onError: (error: AxiosError<{ error_code: string; detail: string }>) => {
        if (error.response?.data.error_code === 'EMAIL_ALREADY_REGISTERED') {
          setError('email', { message: 'This email is already taken.' });
        }
      },
    },
  );
};

```

2024-01-24 08:49 UTC, cruelladevil commented
로그인 페이지 리팩터링 브랜치와 병합하였습니다!
제 커밋을 살려두셔서 저도 fast-foward 되었네요.
[변경사항이 포함된 커밋 링크](https://github.com/girok-web/girok-web/pull/15/files/5f887c5768d5d8689a45ba76aae870617c20e8fb..e7b57bba076da3e352369f17b8f0fef96b03f409) 확인 해주시면 될 것 같아요!

2024-01-24 08:56 UTC, cruelladevil commented on src/pages/SignupPage.tsx
> +  };
플로우를 간략하게 설명드리면,
`react-hook-form submit` -> `api 호출 성공` -> `setSignupData`
형식으로 페이지단에 최종 제출하는데 필요한 데이터를 임시적으로 담고 있습니다.

페이지 상태 - email, verificationCode
password Step이 사실상 최종 제출 - email, verificationCode를 들고와서 password와 함께 제출

이렇게 구성하였는데 이 부분 리뷰가 필요합니다!

2024-01-25 04:45 UTC, jw-r approved these changes
많은 파일에 적용시키느라 고생 많으셨습니다!
너무 잘 적용해주셨네👍

이번 PR은 여기서 approve해도 좋을 것 같습니다!!

2024-01-25 10:22 UTC, cruelladevil commented
## ✅ 적용된 것

- InputField 컴포넌트
- react hook form
- 퍼널

## ❌ 적용되지 않은 것

- react hook form validation
- react query

2024-01-25 10:29 UTC, merged