로그인 페이지 리펙토링
girok-web/girok-web pull request #18
Opened 2024-01-23 09:18 UTC by jw-r

## 🔨 작업 내용

- [x] useFunnel 구현 및 적용
- [x] react query 적용
- [x] password visibility를 SIgnForm.Input 컴포넌트 내부로 추상화
- [x] Addition 컴포넌트 AuthPromptLink 컴포넌트로 추상화
- [x] error 상태와 helperText 상태의 중복 제거

## #️⃣ 연관된 이슈

> 연관된 이슈 번호를 모두 작성

close #13

2024-01-23 12:25 UTC, cruelladevil requested changes
👍 퍼널 적용

2024-01-23 12:25 UTC, jariita commented on src/auth/AuthPromptLink.tsx
> +      <Link to={to} css={{ color: colorPalette.black }}>
css 함수가 빠진 것 같아요!

2024-01-23 12:25 UTC, jariita commented on src/auth/login/components/LoginEmail.tsx
> +        },
💬 정상 케이스와 에러 케이스를 onSettled로 묶어서 처리하는 이유가 있나용??

2024-01-23 12:25 UTC, jariita commented on src/auth/login/components/LoginPassword.tsx
> +        <MoveToReset linkText="Did you forget your password?" />
👍 MoveToReset이라는 컴포넌트가 필요한 정보만 적절히 추상화 된 것 같네요!

2024-01-23 12:25 UTC, jariita commented on src/auth/login/hooks/useLogin.ts
> +}
이런식으로 사용한다면 useMutation의 다른 옵션들은 사용 못하지 않나요?
저는 각각 mutation 훅들을 만들면 좋을 것 같습니다.
게다가 mutatoin 훅은 fetching 함수와 관련있고 함께 관리하는 것이 좋으니, `query.ts`에 있으면 좋을 것 같네요!

```ts
export const useLogionMutation = () => {
  const { mutate: login, ...mutations } = useMutation({ ... });

  return { login, ...mutations };
};
```

### 참고자료

tkdodo - [Practical React Query](https://tkdodo.eu/blog/practical-react-query#create-custom-hooks)

<img width="957" alt="image" src="https://github.com/girok-web/girok-web/assets/87710730/97dc4b63-4ecb-447d-bd9e-037b508d8670">

2024-01-23 12:25 UTC, jariita commented on src/models/utils/NoneEmptyArray.ts
> +export type NonEmptyArray<T> = readonly [T, ...T[]];
readonly가 네이밍에도 나타나있지 않아서 의도가 숨어있다고 생각해요.
NonEmptyArray로 타입을 지정했는데 `push`, `pop`이 왜 안될까 의아할 수도 있을 것 같네요.
Readonly를 따로 사용하는 것은 어떤가요?

```ts
type NonEmptyArray<T> = [T, ...T[]];

const strings: Readonly<NonEmptyArray<string>> = ['a', 'b', 'c', 'd'];
strings.push('e');
//      ~~~~
// Property 'push' does not exist on type 'readonly [string, ...string[]]'.
```

2024-01-23 12:25 UTC, jariita commented on src/models/utils/NoneEmptyArray.ts
파일 이름이 `NoneEmptyArray`가 되었네용

2024-01-23 13:15 UTC, jw-r commented on src/models/utils/NoneEmptyArray.ts
오우 이런 실수도 잡아주시다니 너무 좋네요!

2024-01-23 13:23 UTC, jw-r commented on src/models/utils/NoneEmptyArray.ts
> +export type NonEmptyArray<T> = readonly [T, ...T[]];
실수를 방지하기 위해서 `NonEmptyArray` 타입의 `Readonly`는 선택적으로 결정할 수 없어야 할 것 같아요
`NonEmptyArray` 타입으로 지정된 배열에 `pop` 와 같은 함수를 사용할 수 있다면 빈 배열이 될 가능성이 있기 때문입니다

2024-01-23 13:29 UTC, jw-r commented on src/auth/login/components/LoginEmail.tsx
> +        },
해당 API를 호출했을 때, 결과에 상관없이 200 status 코드를 반환받기 때문입니다.
성공인지 실패인지 판단을 호출에 대한 결과 값인 isRegistered로 판단하고 있어요

onSuccess 콜백함수를 사용한다면 코드를 읽는 입장에서는 성공 시에 대한 처리로 인식하게 될 것이라 생각해요
onSettled을 사용해서 성공 여부에 상관없이 isRegistered의 값에 따라 추후 처리를 결정한다는 것을 표현했습니다

2024-01-23 13:39 UTC, jw-r commented on src/auth/AuthPromptLink.tsx
> +      <Link to={to} css={{ color: colorPalette.black }}>
jsx에 inline으로 작성하는 스타일이라면 css 헬퍼 함수를 사용하는 것과 사용하지 않는 것에 성능적으로 큰 차이는 없다고 합니다

다음의 두 가지를 동시에 만족하는 경우 자바스크립트 객체를 사용해서 가독성을 챙기면 어떨까 생각해요
1. jsx에 스타일을 작성하는 경우
2. props가 필요없는 경우

정민님의 생각이 궁금합니다!

2024-01-23 14:19 UTC, jw-r commented on src/auth/login/hooks/useLogin.ts
> +}
둘 다 로그인을 위한 mutation이라 하나로 묶어두었는데, 정민님의 코맨트를 보니 분리해서 구현하는 편이 좋겠네요!
분리를 진행했습니다👍

다만 query.ts 파일에 작성하는 것에 대해선 한번 더 고민해보고 싶어요

다음의 두 가지 이유 때문입니다

1. use 프리픽스를 사용한 이상 react의 hook 규칙에 따라야 한다는 점에서 hook이라는 폴더에 존재하는 것도 합리적이라고 생각하기 떄문입니다. 공유 hook이 아닌 특정 페이지를 위한 hook 폴더를 만들어 사용하고 있기도 하구요
2. Query와 Mutation은 몇 가지 옵션 혹은 에러 처리를 추가하면 상당히 거대해지기 때문에 하나의 파일에 작성한다면 해당 파일이 방대해질 것이에요. 각각의 파일로 분리해서 작성하는 편이 가독성을 높일 수 있다고 생각해요

다만 `useUser`와 같이 여러 페이지에서 공통으로 사용되는 hook의 경우 외부의 공통 hooks폴더에 위치하게 될 텐대,
기능을 위한 hook과 query, mutation을 위한 훅을 따로 관리하고 싶다면 정민님이 공유해주신 방법대로 query.ts파일에 작성하는 것도 합리적이겠다는 생각이 드네요

현재 저희 프로젝트에 보다 적절한 폴더 구조가 뭔지 조금 더 고민해보고 싶어용🥹

2024-01-24 07:03 UTC, cruelladevil commented on src/auth/login/hooks/useLogin.ts
> +}
1. react query에서 클라이언트 상태와 서버 상태를 구분하듯이, 일반 훅(hooks)과 쿼리 훅(remotes)을 분리하는 것이 좋다고 생각했습니다.
2. 이 부분은 말씀하신대로 각 엔드포인트마다 나눠도 좋다고 생각합니다!

>다만 useUser와 같이 여러 페이지에서 공통으로 사용되는 hook의 경우 외부의 공통 hooks폴더에 위치하게 될 텐대,
기능을 위한 hook과 query, mutation을 위한 훅을 따로 관리하고 싶다면 정민님이 공유해주신 방법대로 query.ts파일에 작성하는 것도 합리적이겠다는 생각이 드네요

넵! 저의 의도를 정확하게 파악하셨네용!
`useUser`와 같이 쿼리 훅을 재사용하는 훅은 `hooks`로 들어가고 쿼리 훅은 `remotes`를 의도했습니다!

2024-01-24 07:05 UTC, cruelladevil commented on src/models/utils/NoneEmptyArray.ts
> +export type NonEmptyArray<T> = readonly [T, ...T[]];
👍 `pop`을 생각하면 제한하도록 하는게 맞는 것 같네요.

2024-01-24 07:13 UTC, cruelladevil approved these changes
이 PR은 아래 코멘트 하나 확인 후 마무리하고,
react-hook-form 및 react query 세부 사항은 새로운 PR에서 진행하면 좋을 것 같습니다!

2024-01-24 07:13 UTC, cruelladevil commented on src/auth/login/hooks/useEmailVerified.ts
> +}
useMutation의 다른 반환값들을 useEmailVerified에서 반환하지 않는 이유가 있을까요??

- https://github.com/girok-web/girok-web/pull/18#discussion_r1463141152

2024-01-24 14:42 UTC, merged