기본 Toast 기능을 구현한다
girok-web/girok-web pull request #36
Opened 2024-01-31 13:41 UTC by jw-r

## 🤷 구현한 기능

Toast 컴포넌트

## 사용
```tsx
const { openToast } = useToast();

<button onClick={() => openToast({ message: 'Resync successfully', width: 'long' })}>토스트 메시지 띄우기</button>
```

## 동작
![화면 기록 2024-01-31 오후 10 35 36](https://github.com/girok-web/girok-web/assets/88191233/9cca9685-103d-4f6d-b9cd-3361d1040dc8)

## 🔨 상세 작업 내용

- [x] useOverlay 구현
- [x] Toast 컴포넌트 구현
  - [x] colorPalette에 Toast 배경 색 추가
  - [x] close svg 파일 생성
- [x] useToast 훅 구현

## 📄 참고 사항

기본 형태의 Toast 기능을 구현했습니다
추후 추가될 기능
- undo 등의 custom 버튼
- promise 이벤트가 끝나기 전까지 사라지지 않도록 하는 option

2024-02-02 10:23 UTC, cruelladevil requested changes
복잡한 기능들이 많아서 2회로 나누어서 리뷰하겠습니다! 🙇‍♂️
궁금한 점이 있는데 페이지 이동간에도 overlay가 유지되는 것이 의도한 바일까요?

2024-02-02 10:23 UTC, jariita commented on src/hooks/use-taost/Toast.tsx
폴더명이 `use-taost`로 오타났어요

2024-02-02 10:23 UTC, jariita commented on src/hooks/use-taost/Toast.tsx
> +        <img src={closeIcon} alt="close" />
close toast라고 더욱 명확하게 해주면 좋을 것 같아요!

2024-02-02 10:23 UTC, jariita commented on src/hooks/use-taost/Toast.tsx
> +  }
이 부분 때문에 애니메이션이 매끄럽지 않은 것 같아요.
튕기는 느낌을 의도하신 것 같은데 튕기는 느낌보다는 흔들리는 느낌이 강하네요 😭

2024-02-02 10:23 UTC, jariita commented on src/hooks/use-taost/Toast.tsx
> +  }
css 부분이어서 코드 스타일이 안맞네용ㅠ `100% {`

2024-02-02 10:23 UTC, jariita commented on src/hooks/use-taost/Toast.tsx
> +  }
💬 fadeUp은 붙여썼던데 fadeOut은 띄워 쓴 이유가 있나용??

2024-02-02 10:23 UTC, jariita commented on src/hooks/use-taost/useToast.tsx
> +  const exitAnimationTimeoutRef = useRef<NodeJS.Timeout | null>(null);
저는 해당 부분 타입스크립트 에러가 나네요.
게다가 실행 환경은 브라우저인데 NodeJS 타입은 아닐 것 같아요!
`ReturnType<typeof setTimeout>`을 사용하면 실행환경 신경쓰지 않고 `타입`은 해결될 것 같아요.
런타임은 또 다른 얘기겠지만요 😭

2024-02-02 10:23 UTC, jariita commented on src/hooks/use-overlay/OverlayProvider.tsx
> +if (process.env.NODE_ENV !== 'production') {
`NODE_ENV`와 `import.meta.env.MODE`는 vite에서 다르다고 합니다.
어떤 의도인지 명확하진 않지만 vite상에서의 mode를 사용하려면 `import.meta.env.MODE`를 사용할 것 같고,
`NODE_ENV`를 사용하려면 package.json에서 명령어를 수정해야 할 것 같네요.

https://ko.vitejs.dev/guide/env-and-mode.html#node-env-and-modes

2024-02-02 10:23 UTC, jariita commented on src/hooks/use-overlay/OverlayProvider.tsx
> +}
한 줄 띄워주면 좋을 것 같네요!

```suggestion
export const OverlayContext = createContext<{
  mount(id: string, element: ReactNode): void;
  unmount(id: string): void;
} | null>(null);

if (process.env.NODE_ENV !== 'production') {
  OverlayContext.displayName = 'OverlayContext';
}
```

2024-02-02 10:23 UTC, jariita commented on src/hooks/use-overlay/OverlayProvider.tsx
> +      const cloned = new Map(overlayById);
😱 Map의 인자에 이터러블이 가능해서 `new Map(map)`이 가능한 거군요! 새로운 것 배워갑니다 👍

2024-02-02 10:23 UTC, jariita commented on src/hooks/use-overlay/useOverlay.tsx
> +  const [id] = useState(() => String(elementId++));
💬 elementId는 number 값을 사용하고, overayId는 string을 사용하는 이유는 무엇인가요?

2024-02-02 17:32 UTC, jw-r commented on src/hooks/use-taost/Toast.tsx
항상 이런 오타를 기가맥히게 잡아주시네요!
꼼꼼히 봐주시는게 느껴집니다!
너무너무너무 좋습니다🤩

2024-02-02 17:40 UTC, jw-r commented on src/hooks/use-taost/Toast.tsx
> +        <img src={closeIcon} alt="close" />
전에 함께 봤던 김석진님의 `Slash PR`이 생각나네요!

이미 `Toast` 컴포넌트 내부에서 close할 것은 Toast로 명백한 상황이라 `closeToast`로 할 필요까지는 없겠다고 생각했습니다!

석진님의 PR과는 조금 차이가 있는데요

컴포넌트 내부에서 선언된 상태가 아닌, 외부에서 받는 prop라는 점입니다
따라서 Toast 컴포넌트를 사용하는 곳에서 다음과 같이 closeToast를 넘기는 형태가 되는데, 이점이 특히 불필요하다고 생각했습니다
```tsx
<Toast
  message={message}
  width={width}
  isOpening={isOpen === true}
  isClosing={isRendered && isOpen === false}
  closeToast={handleClose}
/>
```

`closeToast`라는 prop 명을 사용한다면 `isOpening`, `isClosing` 또한 `isOpeningToast`, `isClosingToast`이 되어야 하는걸까? 하는 생각도 들었구요

이러한 점에 대해서 정민님의 생각을 여쭤보고 싶습니다!!

2024-02-02 17:43 UTC, jw-r commented on src/hooks/use-taost/Toast.tsx
> +  }
저도 이게 참.. 매끄러운 애니메이션을 찾기 어려웠는데요 ㅠㅠㅠ

framer-motion의 bouncing 애니메이션을 참고해보겠습니다!

2024-02-02 17:44 UTC, jw-r commented on src/hooks/use-taost/Toast.tsx
> +  }
허어엉 ㅠㅠ
수정하겠습니다!

2024-02-02 17:44 UTC, jw-r commented on src/hooks/use-taost/Toast.tsx
> +  }
따로 없었습니다!
fadeUp처럼 공백을 제거하겠습니다!

2024-02-02 17:52 UTC, jw-r commented on src/hooks/use-taost/useToast.tsx
> +  const exitAnimationTimeoutRef = useRef<NodeJS.Timeout | null>(null);
정민님 말씀대로 setTimeout 함수는 NodeJS 환경에서 NodeJS.Timeout 객체를, 브라우저 환경에서는 number 타입을 반환하기 때문에 위의 코드는 적절하지 않을 수 있다는 것에 동의합니다!!

`ReturnType<typeof setTimeout>`을 통해 현재 환경에 맞는 적절한 타입을 자동으로 추론할 수 있다고 합니다!!
또 하나 배웠네요🤩
반영하겠습니다!

2024-02-02 17:56 UTC, jw-r commented on src/hooks/use-overlay/OverlayProvider.tsx
> +if (process.env.NODE_ENV !== 'production') {
미쳐 신경쓰지 못했네요!
감사합니다🤩

2024-02-02 17:58 UTC, jw-r commented on src/hooks/use-overlay/OverlayProvider.tsx
> +}
동의합니다!

적용시켰습니다👍

2024-02-02 18:17 UTC, jw-r commented on src/hooks/use-overlay/useOverlay.tsx
> +  const [id] = useState(() => String(elementId++));
Map의 key는 객체를 포함해서 모든 값이 올 수 있지만, 관습적으로 `number` 타입보다는 `string` 값을 사용한다고 합니다

현재 코드에서는 큰 의미가 없지만 `디버깅과 가독성`, `키 값의 유연성`등이 그 이유가 될 거라고 생각해요

예를 들어, Toast와 모달의 overlay를 구분하고자 한다면 `Modal-0`, `Toast-0`과 같이 네임스페이스를 분리할 수 있을 것입니다

2024-02-02 18:47 UTC, jw-r commented on src/hooks/use-taost/Toast.tsx
> +  }
변경 된 애니메이션 확인 부탁드려요~!

2024-02-05 17:48 UTC, cruelladevil commented on src/hooks/use-taost/Toast.tsx
> +        <img src={closeIcon} alt="close" />
라인을 img에 걸었는데 위 onClick의 close 때문에 혼동이 있었네요🫠
`alt`에 대해서 얘기한 것입니다!

2024-02-05 17:50 UTC, jariita commented on src/hooks/use-taost/Toast.tsx
> +  }
👍 훨씬 부드러워졌네요!!

2024-02-05 17:52 UTC, cruelladevil commented on src/hooks/use-taost/Toast.tsx
> +  }
💬 휴먼 에러를 방지하기 위해서 stylelint를 적용하여 자동 formatting 해주는 것이 좋을 것 같네용

2024-02-05 17:59 UTC, cruelladevil requested changes
> 💬 페이지 이동간에도 overlay가 유지되는 것이 의도한 바일까요?

기본 동작으로는 한 번에 하나의 토스트 밖에 안뜨는 것으로 동작하지만,
페이지 이동간에 토스트가 유지되기 때문에 토스트가 겹치는 경우도 생깁니다.
토스트 동작을 명확하게 정의해주어야 할 것 같아요!

![Kapture 2024-02-06 at 02 57 47](https://github.com/girok-web/girok-web/assets/87710730/f6af9d92-f802-4733-84c4-66dc11cc0a46)

2024-02-06 08:56 UTC, jw-r commented on src/hooks/use-taost/Toast.tsx
> +        <img src={closeIcon} alt="close" />
아하!
제가 오해했네요 😭

동의합니다 `close toast`로 수정하겠습니다!

2024-02-06 09:04 UTC, jw-r commented
> > 💬 페이지 이동간에도 overlay가 유지되는 것이 의도한 바일까요?
> 
> 기본 동작으로는 한 번에 하나의 토스트 밖에 안뜨는 것으로 동작하지만, 페이지 이동간에 토스트가 유지되기 때문에 토스트가 겹치는 경우도 생깁니다. 토스트 동작을 명확하게 정의해주어야 할 것 같아요!
> 
> ![Kapture 2024-02-06 at 03 00 29](https://private-user-images.githubusercontent.com/87710730/302385722-fd1caec4-020d-4b1d-85b4-56dd56165d14.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMDk5ODMsIm5iZiI6MTcwNzIwOTY4MywicGF0aCI6Ii84NzcxMDczMC8zMDIzODU3MjItZmQxY2FlYzQtMDIwZC00YjFkLTg1YjQtNTZkZDU2MTY1ZDE0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDA4NTQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiMzI2YWYyNjIxNGM1MDNhNDkxNTMyZDQxNjg0OTkwZWVlOTdiZjQ0MDRiYmQ0ODI5ZjA5M2VmNDc0NTRjNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p-tGivtczGXQvHB7WWNwvjH70wAM1RzOm4PgwHtRfPg) [ ![Kapture 2024-02-06 at 03 00 29](https://private-user-images.githubusercontent.com/87710730/302385722-fd1caec4-020d-4b1d-85b4-56dd56165d14.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMDk5ODMsIm5iZiI6MTcwNzIwOTY4MywicGF0aCI6Ii84NzcxMDczMC8zMDIzODU3MjItZmQxY2FlYzQtMDIwZC00YjFkLTg1YjQtNTZkZDU2MTY1ZDE0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDA4NTQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiMzI2YWYyNjIxNGM1MDNhNDkxNTMyZDQxNjg0OTkwZWVlOTdiZjQ0MDRiYmQ0ODI5ZjA5M2VmNDc0NTRjNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p-tGivtczGXQvHB7WWNwvjH70wAM1RzOm4PgwHtRfPg) ](https://private-user-images.githubusercontent.com/87710730/302385722-fd1caec4-020d-4b1d-85b4-56dd56165d14.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMDk5ODMsIm5iZiI6MTcwNzIwOTY4MywicGF0aCI6Ii84NzcxMDczMC8zMDIzODU3MjItZmQxY2FlYzQtMDIwZC00YjFkLTg1YjQtNTZkZDU2MTY1ZDE0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDA4NTQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiMzI2YWYyNjIxNGM1MDNhNDkxNTMyZDQxNjg0OTkwZWVlOTdiZjQ0MDRiYmQ0ODI5ZjA5M2VmNDc0NTRjNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p-tGivtczGXQvHB7WWNwvjH70wAM1RzOm4PgwHtRfPg) [ ](https://private-user-images.githubusercontent.com/87710730/302385722-fd1caec4-020d-4b1d-85b4-56dd56165d14.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMDk5ODMsIm5iZiI6MTcwNzIwOTY4MywicGF0aCI6Ii84NzcxMDczMC8zMDIzODU3MjItZmQxY2FlYzQtMDIwZC00YjFkLTg1YjQtNTZkZDU2MTY1ZDE0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDA4NTQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiMzI2YWYyNjIxNGM1MDNhNDkxNTMyZDQxNjg0OTkwZWVlOTdiZjQ0MDRiYmQ0ODI5ZjA5M2VmNDc0NTRjNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p-tGivtczGXQvHB7WWNwvjH70wAM1RzOm4PgwHtRfPg)

흐음 동의합니다!
페이지 이동에 따라 두개 이상의 overlay 인스턴스가 호출된다면 토스트가 겹치는 문제가 발생하네요
`Dialog`, `Alert` 등도 `useOverlay`로 구현될 가능성을 배제할 수 없고, 프로젝트에 2개 이상의 모달이 동시에 존재하는 경우도 있기 때문에 하나로 강제하기는 어려울 것 같네요

지금 떠오르는 해결방안은 `ToastProvider`와 `OverlayProvider`를 나눠서 토스트는 가장 최근에 실행된 것 하나만 마운트하는 것인데, 조금 더 고민해보겠습니다🥲

2024-02-06 23:29 UTC, merged