좌측 Sidebar의 UI를 구현한다
girok-web/girok-web pull request #53
Opened 2024-02-08 08:18 UTC by jw-r

## 🔨 작업 내용

좌측 Sidebar 각 카드의 기능을 구현하기 위한 UI 작업입니다

<img width="1512" alt="image" src="https://github.com/girok-web/girok-web/assets/88191233/05d9c190-7455-4dbe-9d70-ad26cad54e31">

- [x] Card 컴포넌트 구현
  - [x] Event Card 컴포넌트 구현
  - [x] Category Card 컴포넌트 구현
  - [x] Todo Card 컴포넌트 구현
- [x] Flex 컴포넌트 구현
- [x] Checkbox 컴포넌트 구현 (custom checkbox type Input)
- [x] Text 컴포넌트 strike prop 추가 (완료된 Todo UI)

## 💬 리뷰 참고사항

- Card Component
Card 컴포넌트의 기본 동작 로직(확장, 축소, content 추가 등)은 모두 숨기고 header와 content만 작성할 수 있도록 구현했습니다
위 컴포넌트 설계에 대해 집중적으로 봐 주셨으면 좋겠습니다

## #️⃣ 연관된 이슈

> 연관된 이슈 번호를 모두 작성

close #52

2024-02-09 17:40 UTC, cruelladevil requested changes
UI만 완성시키는 줄 알았는데 설계까지 고려해서 작성하셨네요!! 👍👍
기능도 추가되면 멋진 UI가 될 것 같아요 최고최고 😄😄

코멘트에 코드 스타일적인 측면이 꽤 있는데 그 부분은 가볍게 생각하셔도 될 것 같아요!
조건부 렌더링 같은 경우도 저는 일단 삼항연산자로 통일시켰는데 false일때 null인 경우는 앰퍼샌드(`&&`)가 편한 부분도 있기 때문에 맞춰보면 좋을 것 같아요~

2024-02-09 17:40 UTC, jariita commented on src/components/Checkbox.tsx
> +  }
💬 input에 대한 스타일을 nested로 지정한 이유가 있나용?

2024-02-09 17:40 UTC, jariita commented on src/components/Checkbox.tsx
> +    </Label>
💬 다른 컴포넌트에서는 label 태그와 input 태그를 평행하게 다루었는데 여기서는 children으로 다룬 이유가 궁금해요!

2024-02-09 17:40 UTC, jariita commented on src/components/Flex.tsx
> +}));
💬 태그드 템플릿으로 하지 않은 이유가 있나용?!

```suggestion
const Flex = styled.div<FlexProps>`
  display: flex;
  align-items: ${({ align }) => align};
  justify-content: ${({ justify }) => justify};
  flex-direction: ${({ direction }) => direction};
`;
```

2024-02-09 17:40 UTC, jariita commented on src/components/Text.tsx
> +  }),
> 💬 태그드 템플릿으로 하지 않은 이유가 있나용?!

💬 위 코멘트와 동문입니다!

2024-02-09 17:40 UTC, jariita commented on src/features/sidebar-card/components/Card.tsx
> +function Card({ header, description, children }: CardProps) {
💬 PropsWithChildren은 제네릭이어서 extends 하지 않아도 됩니다!

```ts
interface CardProps {
  header: ReactNode;
  description?: string;
}

function Card({ header, description, children }: PropsWithChildren<CardProps>) {
```

2024-02-09 17:40 UTC, cruelladevil commented on src/features/sidebar-card/components/Card.tsx
> +  };
💬 펼치고 접는건 아직 동작하지 않는건가요?
기본적으로 다 보여주고 있는데 펼치라고 나오네용

<img width="330" alt="image" src="https://github.com/girok-web/girok-web/assets/87710730/ae7552e2-194d-4b37-9c35-d66bf99b6cd8">

2024-02-09 17:40 UTC, cruelladevil commented on src/features/sidebar-card/components/Card.tsx
> +      )}
💬 개인적인 의견이지만 조건을 변수로 빼는 것도 좋아보입니다.
또한 조건별로 return을 나누는 것도 괜찮아 보이네요.
컨텐츠가 없는 경우는 따로 빼놓았는데 다른 기준은 합쳐 놓은 것이 이해도를 떨어뜨릴수도 있다고 생각해요.

```ts
const 컨텐츠가없는경우 = contentLength === 0;
const 컨텐츠가확장기준보다적은경우 = 0 < contentLength && contentLength <= 확장표시기준개수;
const 컨텐츠가확장기준보다많은경우 = contentLength > 확장표시기준개수;

if (컨텐츠가없는경우) {
  return (
    ...
  );
}

if (컨텐츠가확장기준보다적은경우) {
  return (
    ...
  );
}

if (컨텐츠가확장기준보다많은경우) {
  return (
    ...
  );
}
```

2024-02-09 17:40 UTC, cruelladevil commented on src/features/sidebar-card/components/Card.tsx
> +    >
💬 어떤 컴포넌트(NoContent)는 `<Flex as="tag" />`를 사용하고, 어떤 컴포넌트는 `css`로 flex를 사용하는 기준이 어떻게 되나용?!

2024-02-09 17:40 UTC, cruelladevil commented on src/features/sidebar-card/components/Card.tsx
> +function ExpandCollapseButton({ onClick, isExpand = false }: { onClick: () => void; isExpand: boolean }) {
`isExpand`는 필수값이니 기본값이 필요없을 것 같습니다

2024-02-09 17:40 UTC, cruelladevil commented on src/features/sidebar-card/components/CategoryCard.tsx
> +  }
👍 nested의 좋은 사례인 것 같네요 👍

2024-02-09 17:40 UTC, cruelladevil commented on src/components/Checkbox.tsx
> +  const checked = watch(name);
💬 react-hook-form으로 관리한 이유가 궁금해요!

2024-02-09 17:40 UTC, cruelladevil commented on src/features/sidebar-card/SidebarCard.tsx
> +`;
💬 naming에만 충실한 styled componenet를 선호하시나요?
해당 컴포넌트는 Flex로도 충분한 것 같아서요!

```tsx
function SidebarCard() {
  return (
    <Container>
      <Header />
      <Spacing size={18} />
      <Flex direction="column" gap={24}>
        <TodayEventsCard />
        <TodoListCard />
        <CategoryCard />
      </Flex>
    </Container>
  );
}
```

2024-02-09 17:40 UTC, cruelladevil commented on src/components/Flex.tsx
> +}));
flex에서 gap도 많이 쓰이는 속성인데 추가되면 좋을 것 같네요!

2024-02-09 17:40 UTC, cruelladevil commented on src/features/sidebar-card/SidebarCard.tsx
SidebarCard가 스크롤 되어야 할 것 같네용!
네이밍도 Card들을 포함시키는 컨테이너이니 Cards가 어울릴 것 같습니다!

<img width="1440" alt="image" src="https://github.com/girok-web/girok-web/assets/87710730/7e85309a-ca86-4118-bc11-15f7e3cd0fe1">

2024-02-19 22:33 UTC, jw-r commented on src/features/sidebar-card/components/Card.tsx
> +  };
세부 기능 구현이라 현재 PR에는 포함시키지 않았습니다!

2024-02-19 22:33 UTC, jw-r commented on src/components/Checkbox.tsx
> +  const checked = watch(name);
빠르게 작성하기 용이해서 react-hook-form을 사용해서 구현했습니다!

check 상태를 localStorage에 저장해야하기 때문에 체크 상태를 상위 컴포넌트인 todo card에서 관리하게 될 것이라고 판단했습니다!
때문에 우선 UI가 동작하도록만 구현해뒀습니다👍

2024-02-19 22:33 UTC, jw-r commented on src/components/Checkbox.tsx
> +    </Label>
Label을 하나의 `Flex 컨테이너`와 같이 취급했습니다
`<Flex as='label'>`과 같이 사용할수도 있겠지만, 이경우 런타임에 결정되는 태그로 인해 `htmlFor` 속성을 타입스크립트가 알 수 없었습니다😭

2024-02-19 22:33 UTC, jw-r commented on src/components/Checkbox.tsx
> +  }
큰 의미를 두지 않았습니다!
인라인 스타일은 기왕이면 피하고싶고, 하나의 스타일 컴포넌트를 더 선언할 정도는 아니라고 생각했던 것 같아요!

2024-02-19 22:33 UTC, jw-r commented on src/components/Flex.tsx
> +}));
```tsx
${({ align }) => align};
${({ justify }) => justify};
..
```
위처럼 하나하나 props를 꺼내오는 과정이 귀찮아서 화살표 함수로 작성했었습니다!
일관성을 위해서 태그된 템플릿으로 작성하는 것이 좋겠네요!

2024-02-19 22:33 UTC, jw-r commented on src/components/Text.tsx
> +  }),
```tsx
text-decoration: ${({ strike }) => (strike ? 'line-through' : 'none')};
text-decoration-color: ${({ strike }) => (strike ? 'inherit' : undefined)};
text-decoration-thickness: ${({ strike }) => (strike ? '1px' : undefined)};
```

일관성을 챙기는 건 좋은 것 같은데 위 방식은 좀 귀찮고 보기도 어렵네요..
아래와 같은 방식이 조금 더 보기 편할 수 있다는 생각도 드는데 정민님의 의견이 궁금해요!
태그된 템플릿을 방식을 고수해야 할까요?

```tsx
({ strike }) => ({
  textDecoration: strike ? 'line-through' : 'none',
  textDecorationColor: 'inherit',
  textDecorationThickness: '1px',
}),
```

2024-02-19 22:33 UTC, jw-r commented on src/features/sidebar-card/components/Card.tsx
> +function Card({ header, description, children }: CardProps) {
그렇군요! 꿀팁 얻어갑니다 🤩

다만 요건 스타일의 차이가 될 것 같아요!
`children` 이 `ReactNode` 타입이 아닌 경우가 있어서 저는 컴포넌트의 `Props` 타입을 정의하는 곳에서 `children`의 타입을 정의하는 것을 선호합니다

다음의 방식은 children의 타입을 컴포넌트의 Props 타입 선언에서 처리하고자 하는 방식의 연장선이 된 것 같아요!
```ts
interface CardProps extends PropsWithChildren
```

2024-02-19 22:33 UTC, jw-r commented on src/features/sidebar-card/components/Card.tsx
> +    >
[코맨트](https://github.com/girok-web/girok-web/pull/53/files#r1484557533)가 하나의 예시가 될 것 같습니다

요 부분은 별 생각없이 작성한 것 같습니다
처음부터 완전히 설계하고 컴포넌트를 구현한것이아니라 간략히 만들고 children이나 스타일을 추가해나가다보니 이런 문제들이 많이 보이네요

차차 리펙토링 해 나갈 것 같습니다!

2024-02-19 22:33 UTC, jw-r commented on src/features/sidebar-card/components/Card.tsx
> +    >
ExpandCollapseButton처럼 버튼에 flex를 적용하는 것이 아닌, children을 Flex로 감싸주는 편이 좋을 것 같네요

2024-02-19 22:33 UTC, jw-r commented on src/features/sidebar-card/components/Card.tsx
> +      )}
한국어 변수명을 넣어도 이 부분이 어려웠었는데 너무 좋은 방법이네요!

현재 디자인 요구사항에 `컨텐츠가확장기준보다적은경우`에 대한 UI가 사라져서 기존의 방식으로도 충분해진 것 같은데, 변경 사항 확인하신 후 한번 더 의견 부탁드려요 🤩

2024-02-20 00:42 UTC, cruelladevil commented on src/features/sidebar-card/components/Card.tsx
> +function Card({ header, description, children }: CardProps) {
`children 이 ReactNode 타입이 아닌 경우`에

```ts
interface CardProps extends PropsWithChildren {
  children: string;
}
```

이렇게 하신다는 말씀이신가용?
저는 보통 그 경우에 덮어쓰는 느낌이어서 extends 안하기는 한데
제네릭과 extends는 취향차이이긴 하겠네요!

```ts
interface CardProps {
  children: string;
}
```

2024-02-20 00:49 UTC, cruelladevil commented on src/components/Checkbox.tsx
> +  }
[nested의 좋은 예제 코멘트](https://github.com/girok-web/girok-web/pull/53/files/54bb393f6ba72774f3381d2306887d2085bc5697#r1484597286)처럼 꼭 합성해서 사용해야 하는 경우가 아니라면,
각자 스타일을 가지고 있어야 이해하고 관리하는데 편리하다고 생각해요.
다만, label 컴포넌트이니 input 정도는 nested로 작성해도 괜찮을 것 같네용.

2024-02-20 00:51 UTC, cruelladevil commented on src/components/Text.tsx
> +  }),
아래 두 속성(textDecorationColor, textDecorationThickness)이 `strike`가 없으면 `undefined`인가용?
이 부분은 arrow function으로 작성했을 때의 개념이 익숙치 않아서 잘 이해를 못했습니당 🥺
두 방법 모두 섞어서 사용해도 무방한 것 같아요!

2024-02-20 01:00 UTC, jariita commented on src/features/sidebar-card/components/Card.tsx
> +      )}
제가 확인한 UI는 아래와 같은데 한 번 확인 부탁드려용!

<img width="184" alt="image" src="https://github.com/girok-web/girok-web/assets/87710730/827aacd9-53d1-49d0-a80a-3d6a3b55b282">

default - 컨텐츠가 없는 경우
block <= 6 - 컨텐츠가 확장 기준보다 적은 경우 (확장 버튼 없음)
block > 6 - 컨텐츠가 확장 기준보다 많은 경우 (확장 버튼 있음 - See more, Minimize)

(UI 설명에 block 갯수가 잘못되긴 한것 같습니다)

2024-02-25 21:28 UTC, jw-r commented on src/features/sidebar-card/components/Card.tsx
> +function Card({ header, description, children }: CardProps) {
다음과 같이 사용한다는 말이였어용!

```ts
// children이 string 타입일 때
interface CardProps {
  children: string;
}
```

```ts
// children이 ReactNode일 때
interface CardProps extends PropsWithChildren {
  // ..
}
```

children의 유무 및 타입을 Prop의 타입을 정의하는 인터페이스에서 해결하는 느낌으로 이해하면 좋을 것 같네요!

2024-02-25 21:32 UTC, jw-r commented on src/features/sidebar-card/SidebarCard.tsx
> +`;
네이밍에 충실하면 좋기야 하겠지만, 그럴 목적이라면 다른 컴포넌트 파일로 분리하는 편이 좋다고 생각해요!
정민님 말대로 Flex로 충분히 대체가 가능하겠네요!

2024-02-25 21:40 UTC, jw-r commented on src/components/Text.tsx
> +  }),
```tsx
const Text = styled.span<TextProps>(
  ({ typography = 'body2' }) => typographyMap[typography],
  ({ color = 'black', display, textAlign }) => ({
    color: colorPalette[color],
    display,
    textAlign,
  }),
  ({ strike }) => ({
    textDecoration: strike ? 'line-through' : 'none',
    textDecorationColor: 'inherit',
    textDecorationThickness: '1px',
  }),
);
```

display와 textAlign의 경우 해당 속성이 없다면 undefined가 되지만, `textDecorationColor`, `textDecorationThickness`의 경우는 undefined가 되지 않고 리터럴 값이 적용됩니다
`textDecoration`만 `strike`에 의해 동적으로 적용되네요!

사용할 prop을 한번에 꺼내오거나, `style-lint`처럼 관련있는 스타일을 모아두고자 할 때 유용하게 쓸 수 있을 것 같아요!

2024-02-25 23:12 UTC, jw-r commented on src/features/sidebar-card/SidebarCard.tsx
스크롤 적용 완료했습니다

2024-02-25 23:16 UTC, jw-r commented on src/features/sidebar-card/components/Card.tsx
> +      )}
맞아요!
지금 말씀해주신 것처럼 구현되어있습니다

제가 한 단계 단순해졌다고 했던 이유는 기존 Pigma에는 각 카드의 아래에도 add 버튼이 있었기 때문입니다

2024-02-26 02:15 UTC, cruelladevil commented on src/components/Text.tsx
> +  }),
strike가 undefined면 아래와 같이 적용된다는 말씀이시죠?

```js
{
    textDecoration: 'none',
    textDecorationColor: 'inherit',
    textDecorationThickness: '1px',
}
```

2024-02-26 02:19 UTC, cruelladevil commented on src/features/sidebar-card/components/Card.tsx
> +      )}
기준을 넘어선 만큼 가려지지 않고 다 보이는데, 아직 이 부분은 구현 안된 것 아닌가용??

<img width="319" alt="image" src="https://github.com/girok-web/girok-web/assets/87710730/7bdc6cdb-802c-4372-a08b-bd8f2b2cd339">

2024-02-26 02:28 UTC, cruelladevil approved these changes
1. [strike가 undefined이면 적용되는 css](https://github.com/girok-web/girok-web/pull/53#discussion_r1501973834)
2. [TodoListCard 펼치기 기능](https://github.com/girok-web/girok-web/pull/53#discussion_r1501975432)

첫 번째 코멘트 - 제가 이해한 바가 맞는지 한 번 확인 부탁드려요!
두 번째 코멘트 - TodoListCard의 기능이 정확히 동작하지 않는 것 같아요. 현재 완전히 구현하는 것인지, 후에 수정하는 것인지 알려주시고 그에 맞게 진행해주시면 될 것 같습니다.

두 가지 확인되면 머지하셔도 될 것 같습니다!

2024-02-26 02:33 UTC, jw-r commented on src/components/Text.tsx
> +  }),
맞습니다!

2024-02-26 02:35 UTC, jw-r commented
> 1. [strike가 undefined이면 적용되는 css](https://github.com/girok-web/girok-web/pull/53#discussion_r1501973834)
> 2. [TodoListCard 펼치기 기능](https://github.com/girok-web/girok-web/pull/53#discussion_r1501975432)
> 
> 첫 번째 코멘트 - 제가 이해한 바가 맞는지 한 번 확인 부탁드려요! 두 번째 코멘트 - TodoListCard의 기능이 정확히 동작하지 않는 것 같아요. 현재 완전히 구현하는 것인지, 후에 수정하는 것인지 알려주시고 그에 맞게 진행해주시면 될 것 같습니다.
> 
> 두 가지 확인되면 머지하셔도 될 것 같습니다!

1. 이해하신데로입니다!
2. 현재 기능이 구현되지 않은 상태입니다! 이번 PR이 merge되면 각 카드의 세부 기능을 3개의 pr로 나눠서 구현할 예정입니다

2024-02-26 03:12 UTC, merged